### ISSUE TITLE
Revamp - Authentication

### ISSUE THREAD

**Issue by temanaziz** [ia-toki/bebras-pandai#110]
# Halaman On Bording atau Login via google
![Image](https://github.com/ia-toki/bebras-pandai/assets/48538639/e365fb9a-a513-4818-8553-02c82226b211)

![Image](https://github.com/ia-toki/bebras-pandai/assets/48538639/3689cbb0-50a2-4220-9bd7-2836d70e979e)

![Image](https://github.com/ia-toki/bebras-pandai/assets/48538639/080ed1b8-3667-4784-b6b3-d9baa1c06bb8)

# Halaman Registrasi
![image](https://github.com/ia-toki/bebras-pandai/assets/137871192/17508aaa-05e9-4e5d-a1d0-a1619485d5c4)

Pada halaman ini tidak ada validasi khusus.

AC #1: klik "Daftar" akan menyimpan data user pada database
AC #2: klik "Daftar" akan mengarahkan ke home page

# Task
- [ ] Revamp halaman onboard login atau register lewat Google
- [ ] Apabila sudah pernah register maka langsung ke halaman home
- [ ] Apabila belum pernah register maka langsung ke halaman register
- [ ] Setelah register maka data tersimpan dan setelah login masuk ke home

**Comment by ahmad8taufiq** [comment]
![Image](https://github.com/ia-toki/bebras-pandai/assets/11651227/cc8b84e6-c874-4551-b811-dae26ff84b95)
