### ISSUE TITLE
Revamp: Halaman Soal

### ISSUE THREAD

**Issue by Ridwan22XD** [ia-toki/bebras-pandai#163]
### Halaman Soal Lama
![photo_2024-04-03_04-34-21](https://github.com/ia-toki/bebras-pandai/assets/48538639/cb8eefce-6b9c-4dcf-80ba-ace1c74c7424)

## Halaman Soal Baru
![image](https://github.com/ia-toki/bebras-pandai/assets/48538639/6e5dff45-e08b-442b-9767-ea724d3cfeb2)

![image](https://github.com/ia-toki/bebras-pandai/assets/48538639/e865532c-d1d3-49aa-8f32-f9b88661d4bd)

## Task
- [ ] Perbaiki halaman soal semirip mungkin dengan design (fokus fungsi jalan dulu, desain boleh nggak persis plek)
- [ ] Terdapat fungsi untuk memilih daftar soal - jika soal sudah terisi maka beri penanda (misal icon checklist)
- [ ] Terdapat fungsi button jawab yang apabila sudah dijawab maka akan berubah nama menjadi "Ganti Jawaban"
- [ ] Revamp halaman latihan selesai
- [ ] Revamp halaman waktu selesai

## Desain
- https://www.figma.com/file/iJ08zyApVusFo6ltICjpy6/Bebras-Pandai?type=design&node-id=1-9119&mode=design

**Comment by Ridwan22XD** [comment]
issue sudah dipecah di issue lain
