### ISSUE TITLE
Revamp: Halaman Riwayat Latihan

### ISSUE THREAD

**Issue by Ridwan22XD** [ia-toki/bebras-pandai#164]
### Desain Baru
![image](https://github.com/ia-toki/bebras-pandai/assets/48538639/0e3ba0e6-abf5-4624-b4d5-3c1c86c6d0df)

## Task
- [ ] Membuat halaman riwayat latihan
- [ ] Saat button riwayat latihan di klik maka redirect ke halaman riwayat latihan
- [ ] Halaman riwayat latihan - Tab Sudah Dikerjakan => berisi semua soal yang pernah dikerjakan (latihan minggu ini dan minggu depan)
- [ ] Halaman riwayat latihan - Tab Sudah Dikerjakan => apabila kesempatan ada maka button mulai lagi dapat digunakan dan masuk ke latihan
- [ ] Halaman riwayat latihan - Tab Sudah Dikerjakan => apabila kesempatan habis maka button mulai lagi dihide dan fungsinya dihilangkan
- [ ] Halaman riwayat latihan - Tab Belum Dikerjakan => berisi semua soal yang belum pernah dikerjakan (latihan minggu ini dan minggu depan)
- [ ] Halaman riwayat latihan - Tab Belum Dikerjakan => terdapat button "Kerjakan"
- [ ] Halaman riwayat latihan - Tab Belum Dikerjakan => Apabila soal belum dikerjakan maka button "Kerjakan" di buat disable
- [ ] Halaman riwayat latihan - Tab Belum Dikerjakan => button "Mulai Kerjakan" dapat digunakan dan masuk ke latihan

## Desain
- 
![image](https://github.com/ia-toki/bebras-pandai/assets/48538639/f1018fe4-3c23-430a-9bb9-24524ecd1ce4)

**Comment by Ridwan22XD** [comment]
Mas @reorr ini disimpan di branch dulu, nggak usah di mr ke main ya
