### ISSUE TITLE
Revamp: Halaman Materi

### ISSUE THREAD

**Issue by Ridwan22XD** [ia-toki/bebras-pandai#165]
### Halaman Materi Lama

![photo_2024-04-03_04-52-29](https://github.com/ia-toki/bebras-pandai/assets/48538639/deeda8ff-24d3-4efa-b472-072a0de303e7)

### Halaman Materi Baru
![image](https://github.com/ia-toki/bebras-pandai/assets/48538639/113d6ec7-fe02-4dd9-b823-27c00d842f4f)

## Task
- [x] Perbaikan halaman
- [x] Terdapat slider foto
- [x] Terdapat detail materi dengan desain baru
- [x] dapat melakukan download pada detail materi

## Desain
- https://www.figma.com/file/iJ08zyApVusFo6ltICjpy6/Bebras-Pandai?type=design&node-id=1-9119&mode=design
