### ISSUE TITLE
Update: Menyesuaikan Halaman Home

### ISSUE THREAD

**Issue by Ridwan22XD** [ia-toki/bebras-pandai#170]
# Task
- [x] Halaman Home berisi button "Kerjakan Latihan Minggu Ini" dan "Latihan Minggu Depan"
- [x] button "Kerjakan Latihan Minggu Ini" mengarah ke halaman list quiz (koordinasi dengan mas Hasbi)
- [x] button "Latihan Minggu Depan" menampilkan pop up Comming soon

![image](https://github.com/ia-toki/bebras-pandai/assets/48538639/e38b4bef-f272-4356-8fd9-00250986f68b)

# Desain
- figma - https://www.figma.com/file/iJ08zyApVusFo6ltICjpy6/Bebras-Pandai?type=design&node-id=1-9128&mode=design

**Comment by Ridwan22XD** [comment]
mas @ahmad8taufiq ini buttonnya perlu diperlebar agar tidak kepotong ya "Kerjakan Latihan Minggu Ini"nya

![WhatsApp Image 2024-04-18 at 13 30 15](https://github.com/ia-toki/bebras-pandai/assets/48538639/7cb63b47-d03e-46a7-89e0-3d3ec8fdb510)
