### ISSUE TITLE
Update: Penyesuaian Halaman Setting - Edit Profile

### ISSUE THREAD

**Issue by Ridwan22XD** [ia-toki/bebras-pandai#171]
# Task

- [x] Tambahkan Button Back
- [x] Implementasi Button Back jika diklik maka akan mengembalikan ke halaman sebelumnya 
- [x] Menambahkan Text "Edit Profil"
- [x] Button "Perbarui" diubah menjadi "Simpan"
- [x] Button "Simpan" berubah menjadi warna biru (sesuai desain)
- [x] Hilangkan logo bebras panda
- [ ] Field yang diisi disamakan dengan yang ada di app saat ini

![image](https://github.com/ia-toki/bebras-pandai/assets/48538639/0d5e97bc-6d7d-432e-aa83-86bedd7c66ea)

# Desain
- Figma - https://www.figma.com/file/iJ08zyApVusFo6ltICjpy6/Bebras-Pandai?type=design&node-id=1-9128&mode=design

**Comment by Ridwan22XD** [comment]
mas @Novaari2 ini masih ada yang belum sesuai:

- [ ] Data yang mau di edit belum ngeGET dari data sebelumnya
- [ ] Field kebanyakan (seharusnya hanya 4 seperti sebelumnya => Email, Nama, Asal Sekolah dan Provinsi)
- [ ] Button simpan belum berfungsi
- [ ] Setelah button simpan maka redirect ke halaman setting

## Halaman edit profile sebelumnya
![WhatsApp Image 2024-04-18 at 13 36 47](https://github.com/ia-toki/bebras-pandai/assets/48538639/e8566874-176e-4f94-9998-fe29d2bc397e)
