### ISSUE TITLE
Fixing: Halaman Quiz

### ISSUE THREAD

**Issue by Ridwan22XD** [ia-toki/bebras-pandai#172]
# Task
## Halaman List Quiz
- [x] Quiz list tidak bisa di scroll
- [x] Soal yang tampil duplikate 
- [x] Seharusnya jika memilih "Latihan Minggu Ini" maka semua quiz minggu ini muncul

# Reproduce issue
## Soal duplikate
1. Buka halaman "latihan minggu depan" 
2. Lalu back
3. Buka lagi halaman "latihan minggu depan"

# Desain
figma - https://www.figma.com/file/iJ08zyApVusFo6ltICjpy6/Bebras-Pandai?type=design&node-id=1-9128&mode=design

**Comment by Ridwan22XD** [comment]
mas @reorr ini kenapa diakun saya masih duplikat ya? Apakah harus daftar akun baru?
![WhatsApp Image 2024-04-18 at 13 20 13](https://github.com/ia-toki/bebras-pandai/assets/48538639/b21642e4-79c0-493a-817f-f43a57f5fe02)

**Comment by Ridwan22XD** [comment]
mas itu judulnya jangan "Latihan Minggu Depan" tapi ganti "Latihan Mingguan" @reorr

**Comment by reorr** [comment]
> mas @reorr ini kenapa diakun saya masih duplikat ya? Apakah harus daftar akun baru? ![WhatsApp Image 2024-04-18 at 13 20 13](https://private-user-images.githubusercontent.com/48538639/323488434-b21642e4-79c0-493a-817f-f43a57f5fe02.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MjM3OTgsIm5iZiI6MTcxMzQyMzQ5OCwicGF0aCI6Ii80ODUzODYzOS8zMjM0ODg0MzQtYjIxNjQyZTQtNzljMC00OTNhLTgxN2YtZjQzYTU3ZjVmZTAyLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQwNjU4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MjhkN2ZiNzM4YWZkZTQ0OWRiNDNjOWRkNGViZDA4ZWQ0NDhiZmFhNjVmOGQ2YmY5NTIwN2Q2MTgzODI5NzgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nF3tIdzcJNe-NVt67oU7R58fQLll5fQn38uh4aK46aY)

Bisa pakai akun baru, mas
Atau bisa juga dihapus manual di db karena sudah diregister ke quiz tersebut

**Comment by Ridwan22XD** [comment]
ini tak coba cek dengan akun baru dulu mas
