### ISSUE TITLE
Revamp V2: Revamp Halaman Selesai

### ISSUE THREAD

**Issue by Ridwan22XD** [ia-toki/bebras-pandai#176]
## Task

- [x] Revamp halaman latihan selesai
- [x] Pada halaman latihan selesai jika button "Selesai" diklik maka redirect ke halaman list quiz
![image](https://github.com/ia-toki/bebras-pandai/assets/48538639/5f436714-db80-4d0a-a902-76f56837182c)
- [ ] Revamp halaman waktu habis
- [ ] Pada halaman waktu habis jika button "Selesai" diklik maka redirect ke halaman list quiz
![image](https://github.com/ia-toki/bebras-pandai/assets/48538639/86d54812-05fc-4230-9067-cc4de57a4135)

- [ ] Pada branch tambahkan penanda "Revamp V2"

## Desain
- Figma: https://www.figma.com/file/iJ08zyApVusFo6ltICjpy6/Bebras-Pandai?type=design&node-id=1-9119&mode=design
