### ISSUE TITLE
Revamp V2: Revamp Halaman List

### ISSUE THREAD

**Issue by Ridwan22XD** [ia-toki/bebras-pandai#177]
## Task

- [x] Revamp halaman
- [x] Tulisan "Latihan Yang Pernah Diikuti" ubah menjadi "Ayo Kerjakan" dan ukuran diperkecil
- [x] Jika soal merupakan soal minggu ini maka dapat dikerjakan (button dikerjakan dapat diklik)
- [x] Jika soal merupakan soal minggu depan maka tidak dapat dikerjakan (button dikerjakan disable)
- [x] untuk soal minggu depan jangan lupa keterangan dibagian bawahnya "tanggal latihan dapat dikerjakan"
- [x] Pada branch tambahkan penanda "Revamp V2"

![image](https://github.com/ia-toki/bebras-pandai/assets/48538639/98006c4e-eaa2-476d-a1aa-e338f1185817)

## Desain
1. Figma - https://www.figma.com/file/iJ08zyApVusFo6ltICjpy6/Bebras-Pandai?type=design&node-id=1-9119&mode=design
