### ISSUE TITLE
Revamp V2: Revamp Halaman T&C sebelum mengerjakan soal

### ISSUE THREAD

**Issue by Ridwan22XD** [ia-toki/bebras-pandai#178]
## Task

- [x] Revamp halaman T&C sebelum mengerjakan soal
- [x] Button "Nilai" dihilangkan karena nilai sudah muncul di halaman sebelumnya
![image](https://github.com/ia-toki/bebras-pandai/assets/48538639/7eb98644-f782-46f3-97d3-7c8e29cd860f)
- [ ]  Pada branch tambahkan penanda "Revamp V2"

# Desain 
- Figma: https://www.figma.com/file/iJ08zyApVusFo6ltICjpy6/Bebras-Pandai?type=design&node-id=1-9119&mode=design
