### ISSUE TITLE
Revamp V2: Revamp Halaman Detail Soal

### ISSUE THREAD

**Issue by Ridwan22XD** [ia-toki/bebras-pandai#179]
# Task

- [ ] Revamp Halaman Detail soal
- [ ] Tambahkan button back dan fungsinya dibagian atas
- [ ] Tambahkan tulisan "Bebras Pandai" dibagian atas
- [ ] Hapus logo bebras
- [ ] Tambahkan icon more (menampilkan pop up soal dan berpindah soal) - Bisa didiskusikan seberapa sulit fitur ini di meet
- [ ] Jawaban soal merupakan pop up dari bawah (soal optional dan isian)
- [ ] untuk model ganti jawaban seperti desain nggak usah dikerjakan karena terlalu sulit
- [ ] Pada halaman terakhir button soal selanjutnya diubah menjadi selesai
- [ ] button selesai disable saat semua soal belum dijawab

![image](https://github.com/ia-toki/bebras-pandai/assets/48538639/7d7ecaa1-9876-464d-b26d-37bda6fbb25f)

- [ ]  Pada branch tambahkan penanda "Revamp V2"

# Desain
- Figma: https://www.figma.com/file/iJ08zyApVusFo6ltICjpy6/Bebras-Pandai?type=design&node-id=1-9119&mode=design
